### ISSUE TITLE
README里的图片没了

### ISSUE THREAD

**Issue by jackywu** [U1805/Sogou-emoji-thesaurus#1]
多谢朋友的项目。另外，
1. README里的图片没了；
2. 在Linux版本的搜狗输入法里也能批量导入短语么？

**Comment by U1805** [comment]
感谢提醒
我在 Linux 上一直没能成功装上搜狗输入法，所以也不能给出一个肯定答复
不过 v2.2.0 的更新日志中有提到「新增自定义短语功能」，希望能帮到你
